### ISSUE TITLE
Build on debian jessie fails

### ISSUE THREAD

**Issue by mochoandre** [manupap1/libzoneminder-plugin-openalpr#2]
With error:

W: zoneminder-core: unusual-interpreter usr/bin/zmsystemctl.pl #!/usr/bin/pkexec
Finished running lintian.
Now signing changes and any dsc files...
 signfile zoneminder_1.28.1+nmu1.dsc Emmanuel Papin <manupap01@gmail.com>
gpg: skipped "Emmanuel Papin <manupap01@gmail.com>": secret key not available
gpg: /tmp/debsign.vdpnAumI/zoneminder_1.28.1+nmu1.dsc: clearsign failed: secret key not available
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1295:
running debsign failed
root@debian:/usr/src/ZoneMinder#

**Comment by manupap1** [comment]
Hi,

The build does not fail, only the signing step is failing.
By design the `debuild` command tries to sign some files.
Instead I should mention the following command to avoid this unnecessary/misunderstandable step:
`dpkg-buildpackage -rfakeroot -us -uc`

Emmanuel

**Comment by mochoandre** [comment]
Thanks, I just just about to coment that i found a solution (that one) and post it here for future reference to the guys not so experienced in linux like me.
You can also make "debuild -us -uc" that it compiles fine!

Thanks again

**Comment by 1511993** [comment]
I make `dpkg-buildpackage -rfakeroot -us -uc` also make `debuild -us -uc` but i have an error.
tail: cannot open ‘debian/changelog’ for reading: No such file or directory
what i should do?
