### ISSUE TITLE
Add feature: Only triger alarm on certain license plates

### ISSUE THREAD

**Issue by mochoandre** [manupap1/libzoneminder-plugin-openalpr#3]
It would be a very useful feature if zoneminder only triger an alarm if it detects certain license plate. It could read the license plate from a text file or a DB entry and if it matches will trigger alarm.

Regards and thanks

**Comment by manupap1** [comment]
I have already thought to add this feature in the plugin web page.
I will add it in my todo list.

**Comment by manupap1** [comment]
Feature added
To be tested
