### ISSUE TITLE
Compiling on armhf

### ISSUE THREAD

**Issue by mochoandre** [manupap1/libzoneminder-plugin-openalpr#5]
Hello,
I am trying to compile as by your instructions but i have a problem that when i try to compile OpenALPR with "debuild -uc -us" it only builds libopenalpr-data_2.0.1-0.1_all.deb missing libopenalpr-dev_armhf.deb libopenalpr2_armhf.deb

I can install OpenALPR with "make & make install" but when I try to compile libzoneminder-plugin-openalpr it complains about missing libopenalpr-dev

How can i compile de Development libopenalpr-dev because i try to find a solution and cant find

regards and thanks

**Comment by manupap1** [comment]
Hi,

You should try to replace all occurences of `amd64` by `any` in file `debian/control`.

Regards.

Emmanuel

**Comment by Pinusno** [comment]
Hi Emmanuel,

I ran into the same issue and it solved the problem for me. Many thanks

Karsten

**Comment by mochoandre** [comment]
yup, with your instructions it compiles and install fine!
Thanks again for making me learn a lit bit more of "linux"

regards
