### ISSUE TITLE
build failed: no dependency information found for /usr/local/lib/libopencv_core.so.2.4

### ISSUE THREAD

**Issue by whopperg** [manupap1/libzoneminder-plugin-openalpr#8]
Hi manupap1,

just cloned the new version of the plugin but i got the following error:

dh_strip --dbg-package=libzoneminder-plugin-openalpr-dbg
make[1]: Leaving directory '/downloads/git/libzoneminder-plugin-openalpr'
   dh_makeshlibs
   dh_shlibdeps
dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/libopencv_core.so.2.4 (used by debian/libzoneminder-plugin-openalpr/usr/lib/zoneminder/plugins/libzm_plugin_openalpr.so)
Hint: check if the library actually comes from a package.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/libzoneminder-plugin-openalpr.substvars debian/libzoneminder-plugin-openalpr/usr/lib/zoneminder/plugins/libzm_plugin_openalpr.so returned exit code 2
debian/rules:42: recipe for target 'binary' failed
make: **\* [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed

what i'm missing?
my installed libs of opencv:
ii  libopencv-calib3d2.4:amd64                  2.4.9.1+dfsg-1+deb8u1                amd64        computer vision Camera Calibration library
ii  libopencv-contrib-dev:amd64                 2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-contrib
ii  libopencv-contrib2.4:amd64                  2.4.9.1+dfsg-1+deb8u1                amd64        computer vision contrib library
ii  libopencv-core-dev:amd64                    2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-core
ii  libopencv-core2.4:amd64                     2.4.9.1+dfsg-1+deb8u1                amd64        computer vision core library
ii  libopencv-dev                               2.4.9.1+dfsg-1+deb8u1                amd64        development files for opencv
ii  libopencv-features2d-dev:amd64              2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-features2d
ii  libopencv-features2d2.4:amd64               2.4.9.1+dfsg-1+deb8u1                amd64        computer vision Feature Detection and Descriptor Extraction library
ii  libopencv-flann-dev:amd64                   2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-flann
ii  libopencv-flann2.4:amd64                    2.4.9.1+dfsg-1+deb8u1                amd64        computer vision Clustering and Search in Multi-Dimensional spaces library
ii  libopencv-gpu-dev:amd64                     2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-gpu2.4
ii  libopencv-gpu2.4:amd64                      2.4.9.1+dfsg-1+deb8u1                amd64        computer vision GPU library
ii  libopencv-highgui-dev:amd64                 2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-highgui
ii  libopencv-highgui2.4:amd64                  2.4.9.1+dfsg-1+deb8u1                amd64        computer vision High-level GUI and Media I/O library
ii  libopencv-imgproc-dev:amd64                 2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-imgproc
ii  libopencv-imgproc2.4:amd64                  2.4.9.1+dfsg-1+deb8u1                amd64        computer vision Image Processing library
ii  libopencv-legacy-dev:amd64                  2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-legacy
ii  libopencv-legacy2.4:amd64                   2.4.9.1+dfsg-1+deb8u1                amd64        computer vision legacy library
ii  libopencv-ml-dev:amd64                      2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-ml
ii  libopencv-ml2.4:amd64                       2.4.9.1+dfsg-1+deb8u1                amd64        computer vision Machine Learning library
ii  libopencv-objdetect-dev:amd64               2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-objdetect
ii  libopencv-objdetect2.4:amd64                2.4.9.1+dfsg-1+deb8u1                amd64        computer vision Object Detection library
ii  libopencv-ocl-dev:amd64                     2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-ocl2.4
ii  libopencv-ocl2.4:amd64                      2.4.9.1+dfsg-1+deb8u1                amd64        computer vision OpenCL support library
ii  libopencv-photo-dev:amd64                   2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-photo2.4
ii  libopencv-photo2.4:amd64                    2.4.9.1+dfsg-1+deb8u1                amd64        computer vision computational photography library
ii  libopencv-stitching-dev:amd64               2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-stitching2.4
ii  libopencv-stitching2.4:amd64                2.4.9.1+dfsg-1+deb8u1                amd64        computer vision image stitching library
ii  libopencv-superres-dev:amd64                2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-superres2.4
ii  libopencv-superres2.4:amd64                 2.4.9.1+dfsg-1+deb8u1                amd64        computer vision Super Resolution library
ii  libopencv-ts-dev:amd64                      2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-ts2.4
ii  libopencv-ts2.4:amd64                       2.4.9.1+dfsg-1+deb8u1                amd64        computer vision ts library
ii  libopencv-video-dev:amd64                   2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-video
ii  libopencv-video2.4:amd64                    2.4.9.1+dfsg-1+deb8u1                amd64        computer vision Video analysis library
ii  libopencv-videostab-dev:amd64               2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-videostab2.4
ii  libopencv-videostab2.4:amd64                2.4.9.1+dfsg-1+deb8u1                amd64        computer vision video stabilization library
ii  libopencv2.4-java                           2.4.9.1+dfsg-1+deb8u1                all          Java bindings for the computer vision library
ii  libopencv2.4-jni                            2.4.9.1+dfsg-1+deb8u1                amd64        Java jni library for the computer vision library

*\* the file / symlink exsists:**
/usr/local/lib/libopencv_core.so.2.4: symbolic link to libopencv_core.so.2.4.10

**Comment by manupap1** [comment]
Hi,

You've already experienced a similar issue and your options are the same.
Please refer to https://github.com/ZoneMinder/ZoneMinder/issues/630#issuecomment-69758321

Thanks,

Emmanuel

**Comment by whopperg** [comment]
Man, totally forgot about that :-) thanks for the hint. Give it a try later on
